### GENERAL SETTINGS ###

# Site settings
title: © 渗透测试规范审计平台
brand: Ingeek Co.,Ltd.  ANHUI HEFEI.
description: 基于退火算法的渗透测试规范审计平台
baseurl: "" #important: start with /
url: "http://audit.isisy.com"

highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

permalink: "/:categories/:year/:title/"

excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

plugins:
  - jekyll-toc

sass:
    sass_dir: assets/css
future: true
meow_404: true

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "本站由哨兵安全实验室支持创办"
####
## author-avatar capture from github. visit https://github.com/Bin4xin/bin4xin.github.io/blob/main/_config.yml#L34
## source code from: https://xuexi.erealmsoft.com/2014/11/17/others/jekyll-in-github/#5-%E4%BD%9C%E8%80%85%E5%90%8D%E5%8F%8A%E5%A4%B4%E5%83%8F%E5%8A%A0%E8%BD%BD
## quote code in <index.html line#69> from <"$model"/_primaryindex/index.html> dir
## Github.com/your_username -> avatars头像右键 -> 复制图片地址
## https://avatars.githubusercontent.com/u/57884471?v=4
## so gh_avatars = 57884471
####
writer:
  Bin4xin:
    display_name: "Bin4xin"
    gh_avatars: "57884471"
  Yang2635:
    display_name: "Yang2635"
    gh_avatars: "60431848"
  codecat11:
    display_name: "codecat11"
    gh_avatars: "77820961"
  D3ch4ng:
    display_name: "D3ch4ng"
    gh_avatars: "93568218"
## uplook ⬆⬆⬆⬆
## any questions about <gh_avatars> ;)

include: ['_pages','_primaryindex']
exclude: ['BUILD.md','CHANGELOG.md','README.md','vendor']

# jekyll-archives:
#   enabled: [categories]
#   layout:
#     category: category
#   permalink:
#     category: /categories/:name/
jekyll-archives:
  layouts:
    categories: categories
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

contactMail: "administrator@sentrylab.cn"
# option.
project: anhui-telecom-ecdepartment
#jiangsu-telecom-cybersecdepartment: jiangsu-telecom-cyberSecDepartment
#anhui-jiaokong-group: anhui-jiaokong-group

githubAccess: "https://github.com/sentryCyberSec"
githubRepos: "sentryCyberSec.github.io"
githubCodeRepos: "annealing-plantform"
githubRepos-Branch: "main"
# repos:
githubIO: "https://sentryCyberSec.github.io"
giteeIO: "https://sentryCyberSec.gitee.io"
# Build commit hash strings settings

