name: cache

on:
  [workflow_dispatch]


env:
  download_url_ver: "0.39.1"
#  schedule:
#    - cron: '30 22 12-14 12 *'
# 此表达式为国际时间，每年的十二月十二日到十四日的二十二时三十分
# 换算为北京时间，加上八个小时即每年十二月十三日到十五日的六点三十分

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LSI: 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: cache
        id: cache
        uses: actions/cache@v2
        env:
          CACHE_ID: 1
        with:
          path: /tmp/frp
          key: ${{ runner.os }}-frp-${{ env.CACHE_ID }}-${{ hashFiles('anhui-telecom-ecdepartment/_posts/anhui-telecom-ecdepartment/2021-11-23-FRP-Based-On-Golang.md') }}
          restore-keys: |
            ${{ runner.os }}-frp-${{ env.CACHE_ID }}-
      - name: check
        run: |
          ./scripts/entrypoint.sh cache ${{ env.download_url_ver }}
          ls -la /tmp/frp*/*
      - name: files download
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./scripts/entrypoint.sh cache ${{ env.download_url_ver }}

      # 上传打包文件到远程服务器 visit https://shansan.top/2021/01/19/hexo-blog-synchronization-with-rsync/
      - name: Push Bin Files
        uses: yeshan333/rsync-deploy-action@v1.0.0
        with:
          ssh_login_username: github
          remote_server_ip: ${{ secrets.REMOTE_SERVER_IP }}
          ssh_port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          source_path: /tmp/frp/${{ env.download_url_ver }}
          destination_path: ~/assets/frp
          rsync_args: --exclude="./${{ env.project }}/_site/Gemfile.lock"