name: build sync and reload.

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LSI: 'true'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    

    - name: set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: cache Ruby Bundler
      id: cache
      uses: actions/cache@v2
      env:
        CACHE_ID: 1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-${{ hashFiles('anhui-telecom-ecdepartment/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-${{ env.CACHE_ID }}-
#    - name: Change rubygems loading
#      run: sed -i "/^source/c source 'https://rubygems.org'" Gemfile
#     --path=vendor/bundle
    - name: install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        export work_dir="`pwd`/anhui-telecom-ecdepartment" && cd $work_dir
        bundle install --path=vendor/bundle --jobs=4 --retry=3
        commitString=$(git rev-parse HEAD)
        echo $commitString
        echo "commitString: $commitString" >> _config.yml
    # bundle config set --local path 'vendor/bundle' && 
    - name: run jekyll-build
      run: |
        cd $work_dir
        bundle config set --local path 'vendor/bundle'
        bundle exec jekyll build --trace
    # 上传打包文件到远程服务器
    - name: Push
      uses: yeshan333/rsync-deploy-action@v1.0.0
      with:
        ssh_login_username: github
        remote_server_ip: ${{ secrets.REMOTE_SERVER_IP }}
        ssh_port: 22
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        source_path: ./anhui-telecom-ecdepartment/_site/*
        destination_path: ~/www/anhui-telecom-ecdepartment/
        rsync_args: --exclude="./anhui-telecom-ecdepartment/_site/Gemfile.lock"
